### PR TITLE
Propagate null timestamps and dates

### PR DESCRIPTION
**Pull request by matthewrj**
Fixes https://github.com/blueapron/kafka-connect-protobuf-converter/issues/31

### CODE REVIEW

**Comment by matthewrj** [comment]
I've added the distinction between a struct with default values and a null struct. This means with timestamps, if one is present but set to `seconds = 0, nanos = 0` it will output a timestamp with epoch time, but if timestamp is absent, it will be null.

**Comment by mike9005** [comment]
@matthewrj many thanks for the contribution - GitHub has decided to turn off our CI for reasons we're trying to ascertain - we'll get this reviewed and merged in as soon as possible

**Comment by mike9005** [comment]
@matthewrj - there's an unusual import error in here that's a result of a pre-existing import bug - @bayardneville modified your PR with a fix in #34, and will push a new release to Maven Central soon - we'll let you know when that's available. In the meantime, closing this PR 🙏

**Comment by bayardneville** [comment]
@matthewrj this is included in the [2.3.0 release](https://github.com/blueapron/kafka-connect-protobuf-converter/releases/tag/v2.3.0) and is available in [Maven Central](https://search.maven.org/artifact/com.blueapron/kafka-connect-protobuf-converter/2.3.0/jar). Thanks for the contribution.

**Pull request closed without merging**
